phrase:
  access_token: c18c4feab8692804aa5e46f8e3ca9082c2ffce0bf4fa15e3131b9d6780555aaa
  project_id: ff40dd43e88b60dd72f692e8478b0348

  file_format: simple_json

  push:
    sources:
    - file: en.json
      params:
        file_format: simple_json
        locale_id: en
  pull:
    targets:
    - file: es.json
      params:
        file_format: simple_json
        locale_id: es
    - file: en.json
      params:
        file_format: simple_json
        locale_id: en
